/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CallRecordPublic {
    id: bigint;
    startTime: bigint;
    status: CallStatus;
    endTime?: bigint;
    userId: Principal;
    recipientPhone: string;
    callSid?: string;
    presetId: bigint;
    transcript?: string;
}
export type CallId = bigint;
export interface TurnDetection {
    prefixPaddingMs: bigint;
    threshold: number;
    silenceDurationMs: bigint;
    serverVad: boolean;
}
export type PresetId = bigint;
export interface CallPreset {
    id: bigint;
    toolsEnabled: ToolsEnabled;
    ownerId: Principal;
    voice: Voice;
    voiceId?: string;
    name: string;
    sampleRate: SampleRate;
    systemPrompt: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
}
export type CallPresetMutationResult = {
    __kind__: "ok";
    ok: CallPreset;
} | {
    __kind__: "err";
    err: string;
};
export enum AnsweringPresetStatus {
    pendingVerification = "pendingVerification",
    verified = "verified"
}
export interface AnsweringCaptureOptions {
    saveTranscript: boolean;
    recordAudio: boolean;
    consentConfirmed: boolean;
}
export interface AnsweringPreset {
    id: bigint;
    ownerId: Principal;
    name: string;
    phoneNumber: string;
    systemPrompt: string;
    voice: Voice;
    voiceId?: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
    sampleRate: SampleRate;
    toolsEnabled: ToolsEnabled;
    captureOptions: AnsweringCaptureOptions;
    enabled: boolean;
    verificationStatus: AnsweringPresetStatus;
    webhookSecret: string;
    createdAt: bigint;
    updatedAt: bigint;
    verifiedAt?: bigint;
    lastIncomingAt?: bigint;
}
export interface AnsweringPresetInput {
    name: string;
    phoneNumber: string;
    systemPrompt: string;
    voice: Voice;
    voiceId?: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
    sampleRate: SampleRate;
    toolsEnabled: ToolsEnabled;
    captureOptions: AnsweringCaptureOptions;
    enabled: boolean;
    webhookSecret: string;
}
export type AnsweringPresetMutationResult = {
    __kind__: "ok";
    ok: AnsweringPreset;
} | {
    __kind__: "err";
    err: string;
};
export interface AnsweringLiveSession {
    sessionId: string;
    monitorToken: string;
    callSid: string;
    userId: Principal;
    answeringPresetId: bigint;
    answeringPresetName: string;
    callerPhone: string;
    startedAt: bigint;
    allowedSeconds: bigint;
}
export interface SystemLog {
    level: Variant_info_warn_error;
    message: string;
    timestamp: bigint;
    callId?: bigint;
}
export type InitiateCallResult = {
    __kind__: "ok";
    ok: {
        callSid: string;
        callId: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export enum StripeMode {
    live = "live",
    test = "test"
}
export enum PurchaseIntentStatus {
    canceled = "canceled",
    paid = "paid",
    pending = "pending"
}
export enum CallReservationStatus {
    active = "active",
    canceled = "canceled",
    finished = "finished",
    reserved = "reserved"
}
export interface BillingPackage {
    amountCents: bigint;
    id: string;
    name: string;
    seconds: bigint;
}
export interface BillingStatus {
    availableSeconds: bigint;
    balanceSeconds: bigint;
    packages: Array<BillingPackage>;
    reservedSeconds: bigint;
}
export interface PurchaseIntentPublic {
    amountCents: bigint;
    createdAt: bigint;
    id: string;
    mode: StripeMode;
    packageId: string;
    paidAt?: bigint;
    seconds: bigint;
    status: PurchaseIntentStatus;
    stripeSessionId?: string;
    user: Principal;
}
export type CreatePurchaseIntentResult = {
    __kind__: "ok";
    ok: PurchaseIntentPublic;
} | {
    __kind__: "err";
    err: string;
};
export interface CallReservationPublic {
    allowedSeconds: bigint;
    billedSeconds?: bigint;
    callId: bigint;
    callSid?: string;
    callToken?: string;
    canceledReason?: string;
    createdAt: bigint;
    expiresAt: bigint;
    finishedAt?: bigint;
    id: string;
    presetId: bigint;
    recipientPhone: string;
    startedAt?: bigint;
    status: CallReservationStatus;
    transcript?: string;
    usedSeconds?: bigint;
    user: Principal;
}
export type ReserveCallResult = {
    __kind__: "ok";
    ok: CallReservationPublic;
} | {
    __kind__: "err";
    err: string;
};
export type BillingMutationResult = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface TwilioLine {
    enabled: boolean;
    name: string;
    phoneNumber: string;
}
export interface TwilioLineInput {
    enabled: boolean;
    name: string;
    phoneNumber: string;
}
export type TwilioLineMutationResult = {
    __kind__: "ok";
    ok: Array<TwilioLine>;
} | {
    __kind__: "err";
    err: string;
};
export interface InitiateCallInput {
    recipientPhone: string;
    presetId: bigint;
}
export interface CallPresetInput {
    toolsEnabled: ToolsEnabled;
    voice: Voice;
    voiceId?: string;
    name: string;
    sampleRate: SampleRate;
    systemPrompt: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
}
export interface ToolsEnabled {
    xSearch: boolean;
    webSearch: boolean;
    functionCalling: boolean;
}
export enum AudioFormat {
    pcm = "pcm",
    pcma = "pcma",
    pcmu = "pcmu"
}
export enum CallStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export enum SampleRate {
    hz16000 = "hz16000",
    hz32000 = "hz32000",
    hz22050 = "hz22050",
    hz24000 = "hz24000",
    hz44100 = "hz44100",
    hz48000 = "hz48000",
    hz8000 = "hz8000"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_info_warn_error {
    info = "info",
    warn = "warn",
    error = "error"
}
export enum Voice {
    ara = "ara",
    eve = "eve",
    leo = "leo",
    rex = "rex",
    sal = "sal"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    adminAddPromoMinutes(user: Principal, minutes: bigint): Promise<BillingMutationResult>;
    adminGetSystemLogs(limit: bigint): Promise<Array<SystemLog>>;
    adminListAllCalls(): Promise<Array<CallRecordPublic>>;
    adminListUserCalls(userId: Principal): Promise<Array<CallRecordPublic>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelCallReservation(reservationId: string, reason: string): Promise<BillingMutationResult>;
    createAnsweringPreset(input: AnsweringPresetInput): Promise<AnsweringPresetMutationResult>;
    createPreset(input: CallPresetInput): Promise<CallPreset>;
    createPurchaseIntent(packageId: string): Promise<CreatePurchaseIntentResult>;
    deleteAnsweringPreset(id: PresetId): Promise<boolean>;
    deletePreset(id: PresetId): Promise<boolean>;
    duplicatePreset(id: PresetId): Promise<CallPreset | null>;
    extendCallReservationForServer(reservationId: string): Promise<ReserveCallResult>;
    getAdminConfig(): Promise<{
        hasXaiKey: boolean;
        hasTwilioAuth: boolean;
        twilioFromNumber: string;
        twilioAccountSid: string;
        twilioPhoneNumbers: Array<TwilioLine>;
    }>;
    getBillingPackages(): Promise<Array<BillingPackage>>;
    getCallRecord(id: CallId): Promise<CallRecordPublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getAnsweringPreset(id: PresetId): Promise<AnsweringPreset | null>;
    getMyBillingStatus(): Promise<BillingStatus>;
    getPreset(id: PresetId): Promise<CallPreset | null>;
    initiateCall(input: InitiateCallInput): Promise<InitiateCallResult>;
    isCallerAdmin(): Promise<boolean>;
    listMyAnsweringLiveSessions(): Promise<Array<AnsweringLiveSession>>;
    listMyAnsweringPresets(): Promise<Array<AnsweringPreset>>;
    listMyCalls(): Promise<Array<CallRecordPublic>>;
    listMyPresets(): Promise<Array<CallPreset>>;
    reserveCall(input: InitiateCallInput): Promise<ReserveCallResult>;
    setAdminConfig(xaiApiKey: string, twilioAccountSid: string, twilioAuthToken: string, twilioFromNumber: string): Promise<void>;
    setAnsweringPresetEnabled(id: PresetId, enabled: boolean): Promise<AnsweringPresetMutationResult>;
    setTwilioLine(input: TwilioLineInput): Promise<TwilioLineMutationResult>;
    removeTwilioLine(phoneNumber: string): Promise<TwilioLineMutationResult>;
    setTwilioLineEnabled(phoneNumber: string, enabled: boolean): Promise<TwilioLineMutationResult>;
    twilioWebhook(callSid: string, callStatus: string): Promise<string>;
    updateCallStatus(callId: CallId, status: CallStatus, transcript: string | null): Promise<boolean>;
    updateAnsweringPreset(id: PresetId, input: AnsweringPresetInput): Promise<AnsweringPresetMutationResult>;
    updateAnsweringPresetInstructions(id: PresetId, systemPrompt: string): Promise<AnsweringPresetMutationResult>;
    updatePreset(id: PresetId, input: CallPresetInput): Promise<CallPreset | null>;
    updatePresetInstructions(id: PresetId, systemPrompt: string): Promise<CallPresetMutationResult>;
}
import type { AudioFormat as _AudioFormat, CallPreset as _CallPreset, CallPresetInput as _CallPresetInput, CallRecordPublic as _CallRecordPublic, CallStatus as _CallStatus, InitiateCallResult as _InitiateCallResult, SampleRate as _SampleRate, SystemLog as _SystemLog, ToolsEnabled as _ToolsEnabled, TurnDetection as _TurnDetection, UserRole as _UserRole, Voice as _Voice } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminAddPromoMinutes(arg0: Principal, arg1: bigint): Promise<BillingMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddPromoMinutes(arg0, arg1);
                return from_candid_BillingMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddPromoMinutes(arg0, arg1);
            return from_candid_BillingMutationResult(result);
        }
    }
    async adminGetSystemLogs(arg0: bigint): Promise<Array<SystemLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSystemLogs(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSystemLogs(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListAllCalls(): Promise<Array<CallRecordPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllCalls();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllCalls();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUserCalls(arg0: Principal): Promise<Array<CallRecordPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUserCalls(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUserCalls(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelCallReservation(arg0: string, arg1: string): Promise<BillingMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelCallReservation(arg0, arg1);
                return from_candid_BillingMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelCallReservation(arg0, arg1);
            return from_candid_BillingMutationResult(result);
        }
    }
    async createAnsweringPreset(arg0: AnsweringPresetInput): Promise<AnsweringPresetMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnsweringPreset(to_candid_AnsweringPresetInput(arg0));
                return from_candid_AnsweringPresetMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnsweringPreset(to_candid_AnsweringPresetInput(arg0));
            return from_candid_AnsweringPresetMutationResult(result);
        }
    }
    async createPreset(arg0: CallPresetInput): Promise<CallPreset> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreset(to_candid_CallPresetInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CallPreset_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreset(to_candid_CallPresetInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CallPreset_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPurchaseIntent(arg0: string): Promise<CreatePurchaseIntentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseIntent(arg0);
                return from_candid_CreatePurchaseIntentResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseIntent(arg0);
            return from_candid_CreatePurchaseIntentResult(result);
        }
    }
    async deleteAnsweringPreset(arg0: PresetId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnsweringPreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnsweringPreset(arg0);
            return result;
        }
    }
    async deletePreset(arg0: PresetId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreset(arg0);
            return result;
        }
    }
    async duplicatePreset(arg0: PresetId): Promise<CallPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicatePreset(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicatePreset(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminConfig(): Promise<{
        hasXaiKey: boolean;
        hasTwilioAuth: boolean;
        twilioFromNumber: string;
        twilioAccountSid: string;
        twilioPhoneNumbers: Array<TwilioLine>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminConfig();
            return result;
        }
    }
    async getBillingPackages(): Promise<Array<BillingPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillingPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillingPackages();
            return result;
        }
    }
    async getCallRecord(arg0: CallId): Promise<CallRecordPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRecord(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRecord(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnsweringPreset(arg0: PresetId): Promise<AnsweringPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnsweringPreset(arg0);
                return from_candid_opt_AnsweringPreset(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnsweringPreset(arg0);
            return from_candid_opt_AnsweringPreset(result);
        }
    }
    async getMyBillingStatus(): Promise<BillingStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBillingStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBillingStatus();
            return result;
        }
    }
    async getPreset(arg0: PresetId): Promise<CallPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreset(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreset(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateCall(arg0: InitiateCallInput): Promise<InitiateCallResult> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateCall(arg0);
                return from_candid_InitiateCallResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateCall(arg0);
            return from_candid_InitiateCallResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyAnsweringLiveSessions(): Promise<Array<AnsweringLiveSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAnsweringLiveSessions();
                return result.map(from_candid_AnsweringLiveSession);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAnsweringLiveSessions();
            return result.map(from_candid_AnsweringLiveSession);
        }
    }
    async listMyAnsweringPresets(): Promise<Array<AnsweringPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAnsweringPresets();
                return result.map(from_candid_AnsweringPreset);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAnsweringPresets();
            return result.map(from_candid_AnsweringPreset);
        }
    }
    async listMyCalls(): Promise<Array<CallRecordPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyCalls();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyCalls();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyPresets(): Promise<Array<CallPreset>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyPresets();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyPresets();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async reserveCall(arg0: InitiateCallInput): Promise<ReserveCallResult> {
        if (this.processError) {
            try {
                const result = await this.actor.reserveCall(arg0);
                return from_candid_ReserveCallResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reserveCall(arg0);
            return from_candid_ReserveCallResult(result);
        }
    }
    async extendCallReservationForServer(arg0: string): Promise<ReserveCallResult> {
        if (this.processError) {
            try {
                const result = await this.actor.extendCallReservationForServer(arg0);
                return from_candid_ReserveCallResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.extendCallReservationForServer(arg0);
            return from_candid_ReserveCallResult(result);
        }
    }
    async setAdminConfig(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminConfig(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminConfig(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setAnsweringPresetEnabled(arg0: PresetId, arg1: boolean): Promise<AnsweringPresetMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnsweringPresetEnabled(arg0, arg1);
                return from_candid_AnsweringPresetMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnsweringPresetEnabled(arg0, arg1);
            return from_candid_AnsweringPresetMutationResult(result);
        }
    }
    async setTwilioLine(arg0: TwilioLineInput): Promise<TwilioLineMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setTwilioLine(arg0);
                return from_candid_TwilioLineMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTwilioLine(arg0);
            return from_candid_TwilioLineMutationResult(result);
        }
    }
    async removeTwilioLine(arg0: string): Promise<TwilioLineMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTwilioLine(arg0);
                return from_candid_TwilioLineMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTwilioLine(arg0);
            return from_candid_TwilioLineMutationResult(result);
        }
    }
    async setTwilioLineEnabled(arg0: string, arg1: boolean): Promise<TwilioLineMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setTwilioLineEnabled(arg0, arg1);
                return from_candid_TwilioLineMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTwilioLineEnabled(arg0, arg1);
            return from_candid_TwilioLineMutationResult(result);
        }
    }
    async twilioWebhook(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.twilioWebhook(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.twilioWebhook(arg0, arg1);
            return result;
        }
    }
    async updateCallStatus(arg0: CallId, arg1: CallStatus, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallStatus(arg0, to_candid_CallStatus_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateAnsweringPreset(arg0: PresetId, arg1: AnsweringPresetInput): Promise<AnsweringPresetMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnsweringPreset(arg0, to_candid_AnsweringPresetInput(arg1));
                return from_candid_AnsweringPresetMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnsweringPreset(arg0, to_candid_AnsweringPresetInput(arg1));
            return from_candid_AnsweringPresetMutationResult(result);
        }
    }
    async updateAnsweringPresetInstructions(arg0: PresetId, arg1: string): Promise<AnsweringPresetMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnsweringPresetInstructions(arg0, arg1);
                return from_candid_AnsweringPresetMutationResult(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnsweringPresetInstructions(arg0, arg1);
            return from_candid_AnsweringPresetMutationResult(result);
        }
    }
    async updatePreset(arg0: PresetId, arg1: CallPresetInput): Promise<CallPreset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreset(arg0, to_candid_CallPresetInput_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreset(arg0, to_candid_CallPresetInput_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePresetInstructions(arg0: PresetId, arg1: string): Promise<CallPresetMutationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePresetInstructions(arg0, arg1);
                return from_candid_CallPresetMutationResult(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePresetInstructions(arg0, arg1);
            return from_candid_CallPresetMutationResult(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_text(value: [] | [string]): string | undefined {
    return value.length === 0 ? undefined : value[0];
}
function from_candid_opt_nat(value: [] | [bigint]): bigint | undefined {
    return value.length === 0 ? undefined : value[0];
}
function from_candid_StripeMode(value: { live: null } | { test: null }): StripeMode {
    return "test" in value ? StripeMode.test : StripeMode.live;
}
function from_candid_PurchaseIntentStatus(value: { canceled: null } | { paid: null } | { pending: null }): PurchaseIntentStatus {
    return "canceled" in value ? PurchaseIntentStatus.canceled : "paid" in value ? PurchaseIntentStatus.paid : PurchaseIntentStatus.pending;
}
function from_candid_CallReservationStatus(value: { active: null } | { canceled: null } | { finished: null } | { reserved: null }): CallReservationStatus {
    return "active" in value ? CallReservationStatus.active : "canceled" in value ? CallReservationStatus.canceled : "finished" in value ? CallReservationStatus.finished : CallReservationStatus.reserved;
}
function from_candid_PurchaseIntentPublic(value: any): PurchaseIntentPublic {
    return {
        amountCents: value.amountCents,
        createdAt: value.createdAt,
        id: value.id,
        mode: from_candid_StripeMode(value.mode),
        packageId: value.packageId,
        paidAt: from_candid_opt_nat(value.paidAt),
        seconds: value.seconds,
        status: from_candid_PurchaseIntentStatus(value.status),
        stripeSessionId: from_candid_opt_text(value.stripeSessionId),
        user: value.user
    };
}
function from_candid_CreatePurchaseIntentResult(value: any): CreatePurchaseIntentResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PurchaseIntentPublic(value.ok)
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_CallReservationPublic(value: any): CallReservationPublic {
    return {
        allowedSeconds: value.allowedSeconds,
        billedSeconds: from_candid_opt_nat(value.billedSeconds),
        callId: value.callId,
        callSid: from_candid_opt_text(value.callSid),
        callToken: from_candid_opt_text(value.callToken),
        canceledReason: from_candid_opt_text(value.canceledReason),
        createdAt: value.createdAt,
        expiresAt: value.expiresAt,
        finishedAt: from_candid_opt_nat(value.finishedAt),
        id: value.id,
        presetId: value.presetId,
        recipientPhone: value.recipientPhone,
        startedAt: from_candid_opt_nat(value.startedAt),
        status: from_candid_CallReservationStatus(value.status),
        transcript: from_candid_opt_text(value.transcript),
        usedSeconds: from_candid_opt_nat(value.usedSeconds),
        user: value.user
    };
}
function from_candid_ReserveCallResult(value: any): ReserveCallResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CallReservationPublic(value.ok)
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_BillingMutationResult(value: any): BillingMutationResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_TwilioLine(value: any): TwilioLine {
    return {
        enabled: value.enabled,
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_TwilioLineMutationResult(value: any): TwilioLineMutationResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok.map(from_candid_TwilioLine)
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_AnsweringPresetStatus(value: any): AnsweringPresetStatus {
    return "verified" in value ? AnsweringPresetStatus.verified : AnsweringPresetStatus.pendingVerification;
}
function from_candid_AnsweringPreset(value: any): AnsweringPreset {
    return {
        id: value.id,
        ownerId: value.ownerId,
        name: value.name,
        phoneNumber: value.phoneNumber,
        systemPrompt: value.systemPrompt,
        voice: from_candid_Voice_n25(undefined as any, undefined as any, value.voice),
        voiceId: from_candid_opt_text(value.voiceId),
        turnDetection: value.turnDetection,
        audioFormat: from_candid_AudioFormat_n29(undefined as any, undefined as any, value.audioFormat),
        sampleRate: from_candid_SampleRate_n27(undefined as any, undefined as any, value.sampleRate),
        toolsEnabled: value.toolsEnabled,
        captureOptions: value.captureOptions,
        enabled: value.enabled,
        verificationStatus: from_candid_AnsweringPresetStatus(value.verificationStatus),
        webhookSecret: value.webhookSecret,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        verifiedAt: from_candid_opt_nat(value.verifiedAt),
        lastIncomingAt: from_candid_opt_nat(value.lastIncomingAt)
    };
}
function from_candid_AnsweringPresetMutationResult(value: any): AnsweringPresetMutationResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AnsweringPreset(value.ok)
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_CallPresetMutationResult(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: any): CallPresetMutationResult {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CallPreset_n23(_uploadFile, _downloadFile, value.ok)
    } : {
        __kind__: "err",
        err: value.err
    };
}
function from_candid_opt_AnsweringPreset(value: [] | [any]): AnsweringPreset | null {
    return value.length === 0 ? null : from_candid_AnsweringPreset(value[0]);
}
function from_candid_AnsweringLiveSession(value: any): AnsweringLiveSession {
    return {
        sessionId: value.sessionId,
        monitorToken: value.monitorToken,
        callSid: value.callSid,
        userId: value.userId,
        answeringPresetId: value.answeringPresetId,
        answeringPresetName: value.answeringPresetName,
        callerPhone: value.callerPhone,
        startedAt: value.startedAt,
        allowedSeconds: value.allowedSeconds
    };
}
function to_candid_AnsweringPresetInput(value: AnsweringPresetInput): any {
    return {
        name: value.name,
        phoneNumber: value.phoneNumber,
        systemPrompt: value.systemPrompt,
        voice: to_candid_Voice_n17(undefined as any, undefined as any, value.voice),
        voiceId: to_candid_opt_n42(undefined as any, undefined as any, value.voiceId ?? null),
        turnDetection: value.turnDetection,
        audioFormat: to_candid_AudioFormat_n21(undefined as any, undefined as any, value.audioFormat),
        sampleRate: to_candid_SampleRate_n19(undefined as any, undefined as any, value.sampleRate),
        toolsEnabled: value.toolsEnabled,
        captureOptions: value.captureOptions,
        enabled: value.enabled,
        webhookSecret: value.webhookSecret
    };
}
function from_candid_AudioFormat_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioFormat): AudioFormat {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_CallPreset_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallPreset): CallPreset {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CallRecordPublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallRecordPublic): CallRecordPublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_InitiateCallResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InitiateCallResult): InitiateCallResult {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SampleRate_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SampleRate): SampleRate {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SystemLog_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemLog): SystemLog {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Voice_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Voice): Voice {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallPreset]): CallPreset | null {
    return value.length === 0 ? null : from_candid_CallPreset_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallRecordPublic]): CallRecordPublic | null {
    return value.length === 0 ? null : from_candid_CallRecordPublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    toolsEnabled: _ToolsEnabled;
    ownerId: Principal;
    voice: _Voice;
    voiceId: [] | [string];
    name: string;
    sampleRate: _SampleRate;
    systemPrompt: string;
    turnDetection: _TurnDetection;
    audioFormat: _AudioFormat;
}): {
    id: bigint;
    toolsEnabled: ToolsEnabled;
    ownerId: Principal;
    voice: Voice;
    voiceId?: string;
    name: string;
    sampleRate: SampleRate;
    systemPrompt: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
} {
    return {
        id: value.id,
        toolsEnabled: value.toolsEnabled,
        ownerId: value.ownerId,
        voice: from_candid_Voice_n25(_uploadFile, _downloadFile, value.voice),
        voiceId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.voiceId)),
        name: value.name,
        sampleRate: from_candid_SampleRate_n27(_uploadFile, _downloadFile, value.sampleRate),
        systemPrompt: value.systemPrompt,
        turnDetection: value.turnDetection,
        audioFormat: from_candid_AudioFormat_n29(_uploadFile, _downloadFile, value.audioFormat)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: {
        info: null;
    } | {
        warn: null;
    } | {
        error: null;
    };
    message: string;
    timestamp: bigint;
    callId: [] | [bigint];
}): {
    level: Variant_info_warn_error;
    message: string;
    timestamp: bigint;
    callId?: bigint;
} {
    return {
        level: from_candid_variant_n4(_uploadFile, _downloadFile, value.level),
        message: value.message,
        timestamp: value.timestamp,
        callId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.callId))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _CallStatus;
    endTime: [] | [bigint];
    userId: Principal;
    recipientPhone: string;
    callSid: [] | [string];
    presetId: bigint;
    transcript: [] | [string];
}): {
    id: bigint;
    startTime: bigint;
    status: CallStatus;
    endTime?: bigint;
    userId: Principal;
    recipientPhone: string;
    callSid?: string;
    presetId: bigint;
    transcript?: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_CallStatus_n9(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endTime)),
        userId: value.userId,
        recipientPhone: value.recipientPhone,
        callSid: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.callSid)),
        presetId: value.presetId,
        transcript: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.transcript))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): CallStatus {
    return "pending" in value ? CallStatus.pending : "completed" in value ? CallStatus.completed : "inProgress" in value ? CallStatus.inProgress : "failed" in value ? CallStatus.failed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ara: null;
} | {
    eve: null;
} | {
    leo: null;
} | {
    rex: null;
} | {
    sal: null;
}): Voice {
    return "ara" in value ? Voice.ara : "eve" in value ? Voice.eve : "leo" in value ? Voice.leo : "rex" in value ? Voice.rex : "sal" in value ? Voice.sal : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hz16000: null;
} | {
    hz32000: null;
} | {
    hz22050: null;
} | {
    hz24000: null;
} | {
    hz44100: null;
} | {
    hz48000: null;
} | {
    hz8000: null;
}): SampleRate {
    return "hz16000" in value ? SampleRate.hz16000 : "hz32000" in value ? SampleRate.hz32000 : "hz22050" in value ? SampleRate.hz22050 : "hz24000" in value ? SampleRate.hz24000 : "hz44100" in value ? SampleRate.hz44100 : "hz48000" in value ? SampleRate.hz48000 : "hz8000" in value ? SampleRate.hz8000 : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pcm: null;
} | {
    pcma: null;
} | {
    pcmu: null;
}): AudioFormat {
    return "pcm" in value ? AudioFormat.pcm : "pcma" in value ? AudioFormat.pcma : "pcmu" in value ? AudioFormat.pcmu : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        websocketUrl: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        websocketUrl: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        callSid: string;
        callId: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        callSid: string;
        callId: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    info: null;
} | {
    warn: null;
} | {
    error: null;
}): Variant_info_warn_error {
    return "info" in value ? Variant_info_warn_error.info : "warn" in value ? Variant_info_warn_error.warn : "error" in value ? Variant_info_warn_error.error : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SystemLog>): Array<SystemLog> {
    return value.map((x)=>from_candid_SystemLog_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallPreset>): Array<CallPreset> {
    return value.map((x)=>from_candid_CallPreset_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallRecordPublic>): Array<CallRecordPublic> {
    return value.map((x)=>from_candid_CallRecordPublic_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AudioFormat_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioFormat): _AudioFormat {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CallPresetInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallPresetInput): _CallPresetInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_CallStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SampleRate_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleRate): _SampleRate {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Voice_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Voice): _Voice {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toolsEnabled: ToolsEnabled;
    voice: Voice;
    voiceId?: string;
    name: string;
    sampleRate: SampleRate;
    systemPrompt: string;
    turnDetection: TurnDetection;
    audioFormat: AudioFormat;
}): {
    toolsEnabled: _ToolsEnabled;
    voice: _Voice;
    voiceId: [] | [string];
    name: string;
    sampleRate: _SampleRate;
    systemPrompt: string;
    turnDetection: _TurnDetection;
    audioFormat: _AudioFormat;
} {
    return {
        toolsEnabled: value.toolsEnabled,
        voice: to_candid_Voice_n17(_uploadFile, _downloadFile, value.voice),
        voiceId: to_candid_opt_n42(_uploadFile, _downloadFile, value.voiceId ?? null),
        name: value.name,
        sampleRate: to_candid_SampleRate_n19(_uploadFile, _downloadFile, value.sampleRate),
        systemPrompt: value.systemPrompt,
        turnDetection: value.turnDetection,
        audioFormat: to_candid_AudioFormat_n21(_uploadFile, _downloadFile, value.audioFormat)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Voice): {
    ara: null;
} | {
    eve: null;
} | {
    leo: null;
} | {
    rex: null;
} | {
    sal: null;
} {
    return value == Voice.ara ? {
        ara: null
    } : value == Voice.eve ? {
        eve: null
    } : value == Voice.leo ? {
        leo: null
    } : value == Voice.rex ? {
        rex: null
    } : value == Voice.sal ? {
        sal: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SampleRate): {
    hz16000: null;
} | {
    hz32000: null;
} | {
    hz22050: null;
} | {
    hz24000: null;
} | {
    hz44100: null;
} | {
    hz48000: null;
} | {
    hz8000: null;
} {
    return value == SampleRate.hz16000 ? {
        hz16000: null
    } : value == SampleRate.hz32000 ? {
        hz32000: null
    } : value == SampleRate.hz22050 ? {
        hz22050: null
    } : value == SampleRate.hz24000 ? {
        hz24000: null
    } : value == SampleRate.hz44100 ? {
        hz44100: null
    } : value == SampleRate.hz48000 ? {
        hz48000: null
    } : value == SampleRate.hz8000 ? {
        hz8000: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioFormat): {
    pcm: null;
} | {
    pcma: null;
} | {
    pcmu: null;
} {
    return value == AudioFormat.pcm ? {
        pcm: null
    } : value == AudioFormat.pcma ? {
        pcma: null
    } : value == AudioFormat.pcmu ? {
        pcmu: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == CallStatus.pending ? {
        pending: null
    } : value == CallStatus.completed ? {
        completed: null
    } : value == CallStatus.inProgress ? {
        inProgress: null
    } : value == CallStatus.failed ? {
        failed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
