/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was generated by @tanstack/router-plugin
// If you're using this file, please don't manually modify it.
// Consider re-running the command to regenerate it.

import { createFileRoute, createRootRoute } from "@tanstack/react-router";

import { Route as rootRoute } from "./routes/__root";
import { Route as AdminDashboardImport } from "./routes/admin/dashboard";
import { Route as AdminLogsImport } from "./routes/admin/logs";
import { Route as AdminUsersImport } from "./routes/admin/users";
import { Route as IndexImport } from "./routes/index";
import { Route as UserAnsweringImport } from "./routes/user/answering";
import { Route as UserDashboardImport } from "./routes/user/dashboard";
import { Route as UserHistoryImport } from "./routes/user/history";
import { Route as UserSettingsImport } from "./routes/user/settings";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const UserDashboardRoute = UserDashboardImport.update({
  id: "/user/dashboard",
  path: "/user/dashboard",
  getParentRoute: () => rootRoute,
} as never);

const UserAnsweringRoute = UserAnsweringImport.update({
  id: "/user/answering",
  path: "/user/answering",
  getParentRoute: () => rootRoute,
} as never);

const UserHistoryRoute = UserHistoryImport.update({
  id: "/user/history",
  path: "/user/history",
  getParentRoute: () => rootRoute,
} as never);

const UserSettingsRoute = UserSettingsImport.update({
  id: "/user/settings",
  path: "/user/settings",
  getParentRoute: () => rootRoute,
} as never);

const AdminDashboardRoute = AdminDashboardImport.update({
  id: "/admin/dashboard",
  path: "/admin/dashboard",
  getParentRoute: () => rootRoute,
} as never);

const AdminUsersRoute = AdminUsersImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => rootRoute,
} as never);

const AdminLogsRoute = AdminLogsImport.update({
  id: "/admin/logs",
  path: "/admin/logs",
  getParentRoute: () => rootRoute,
} as never);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/user/answering": typeof UserAnsweringRoute;
  "/user/dashboard": typeof UserDashboardRoute;
  "/user/history": typeof UserHistoryRoute;
  "/user/settings": typeof UserSettingsRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/logs": typeof AdminLogsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/user/answering": typeof UserAnsweringRoute;
  "/user/dashboard": typeof UserDashboardRoute;
  "/user/history": typeof UserHistoryRoute;
  "/user/settings": typeof UserSettingsRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/logs": typeof AdminLogsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/user/answering": typeof UserAnsweringRoute;
  "/user/dashboard": typeof UserDashboardRoute;
  "/user/history": typeof UserHistoryRoute;
  "/user/settings": typeof UserSettingsRoute;
  "/admin/dashboard": typeof AdminDashboardRoute;
  "/admin/users": typeof AdminUsersRoute;
  "/admin/logs": typeof AdminLogsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/user/answering"
    | "/user/dashboard"
    | "/user/history"
    | "/user/settings"
    | "/admin/dashboard"
    | "/admin/users"
    | "/admin/logs";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/user/answering"
    | "/user/dashboard"
    | "/user/history"
    | "/user/settings"
    | "/admin/dashboard"
    | "/admin/users"
    | "/admin/logs";
  id:
    | "__root__"
    | "/"
    | "/user/answering"
    | "/user/dashboard"
    | "/user/history"
    | "/user/settings"
    | "/admin/dashboard"
    | "/admin/users"
    | "/admin/logs";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  UserAnsweringRoute: typeof UserAnsweringRoute;
  UserDashboardRoute: typeof UserDashboardRoute;
  UserHistoryRoute: typeof UserHistoryRoute;
  UserSettingsRoute: typeof UserSettingsRoute;
  AdminDashboardRoute: typeof AdminDashboardRoute;
  AdminUsersRoute: typeof AdminUsersRoute;
  AdminLogsRoute: typeof AdminLogsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  UserAnsweringRoute,
  UserDashboardRoute,
  UserHistoryRoute,
  UserSettingsRoute,
  AdminDashboardRoute,
  AdminUsersRoute,
  AdminLogsRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren);

/* prettier-ignore-end */
